config/routes.rb
Rails.application.routes.draw do

  Rails.application.routes.draw do
    namespace :api do
      namespace :v1 do
        devise_for :users, controllers: { registrations: 'api/v1/registrations',
                                          sessions:       'api/v1/sessions'}
        resources :votes, only: [:create, :update]
      end
    end
  end

  root 'parks#index'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show]

  resources :parks do
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end

  resources :reviews, only: :none do
    resources :votes, only: [:create, :update]
  end
end

app/models/park.rb
class Park < ActiveRecord::Base
  has_many :reviews
  belongs_to :user

  validates :title, presence: true
  validates :location, presence: true
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :authorize_user, only: [:destroy]
  before_action :park, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search] == ""
      parks = Park.none
    elsif params[:search]
      parks = Park.where("title ILIKE ?", "%#{params[:search]}%")
    else
      parks = Park.all
    end
    park_sort = parks.sort_by { |park| park.reviews.average(:rating).to_f }.reverse!
    @parks = Kaminari.paginate_array(park_sort).page(params[:page])
  end

  def show
    @review = Review.new
    park_reviews = Review.where(park_id: park)
    @reviews = park_reviews.order(created_at: :desc).page params[:page]
    @rating = @park.reviews.average(:rating)
    if @rating.nil?
      @rating = "N/A"
    else
      @rating = @rating.round(1)
    end
  end

  def new
    @park = Park.new
  end

  def create
    @park = Park.new(park_params)
    @park.user_id = current_user.id

    if @park.save
      flash[:success] = "Park successfully created!"
      redirect_to root_path
    else
      flash[:notice] = @park.errors.full_messages
      render 'new'
    end
  end

  def edit
  end

  def update
    if @park.update(park_params)
      flash[:notice] = "You have successfully updated your question!"
      redirect_to @park
    else
      flash.now[:notice] = "Invalid input."
      render 'edit'
    end
  end

  def destroy
    if @park.destroy
      flash[:notice] = "You have deleted park successfully!"
      redirect_to root_path
    else
      flash[:notice] = "You failed to delete park!"
      render :show
    end
  end

  private

  def park
    @park ||= Park.find(params[:id])
  end

  def park_params
    params.require(:park).permit(
      :title,
      :location,
      :rating,
      :bathroom,
      :picnic,
      :pets,
      :basketball,
      :baseball,
      :user_id
    )
  end
end

app/views/parks/_park.html.erb
<div class="list-item">
  <div class="row" data-equalizer>
    <li>
      <div class="park-info small-4 column" data-equalizer-watch>
        <p>
          <%= link_to park.title, park_path(park) %><br>
          <%= park.location %>
        </p>
      </div>
      <div class="park-icons small-6 column" data-equalizer-watch>
        <%= image_tag("/images/bathroom.png", size:"40") if park.bathroom %>
        <%= image_tag("/images/picnic.png", size:"40") if park.picnic %>
        <%= image_tag("/images/pet.png", size:"40") if park.pets %>
        <%= image_tag("/images/basketball.png", size:"40") if park.basketball %>
        <%= image_tag("/images/baseball.png", size:"40") if park.baseball %>
      </div>
      <div class="index-rating small-2 column" data-equalizer-watch>
        <p>
          <% unless park.reviews.average(:rating).nil? %>
          <%= park.reviews.average(:rating).round(1) %>
          <% else %>
          <%= "N/A" %>
          <% end %>
        </p>
      </div>
    </li>
  </div>
</div>

app/views/parks/edit.html.erb
<div class="review-title small-8 small-centered column text-center">
  <h1 class="review-title">Edit Park Form</h1>
  <%= render "layouts/park_form" %>
</div>

app/views/parks/index.html.erb
<% if params[:search].present? || params[:search] == "" %>
  <div class="text-center">
    <h1>Search Results!</h1>
  </div>
<% else %>
  <div class="text-center">
    <h1>PARKS</h1>
  </div>
<% end %>

<% if @parks.none? || params[:search] == "" %>
  <h5>No results found!</h5>
<% end %>

<% if user_signed_in? %>
<div class="row text-center">
  <div class="small-centered small-2 columns button small">
    <%= link_to "New Park", new_park_path, class: "new" %>
  </div>
</div>
<% end %>

<ul class="small-10 small-centered column">
  <%= render @parks %>
</ul>

<div class="text-center forgot-pass">
  <%= paginate @parks %>
</div>

app/views/parks/new.html.erb
<%if @error_message != nil%>
  <h3><%=@error_message%></h3>
<%end%>

<div class="review-title small-8 small-centered column text-center">
  <h1 class="review-title">New Park Form</h1>
  <%= render "layouts/park_form" %>
</div>

app/views/parks/show.html.erb
<div class="row text-center">

  <h1><%= @park.title%></h1>
  <h3 class="park-show-location"><%= @park.location %></h3>
  <h2 class="park-show-rating">
    <% unless @park.reviews.average(:rating).nil? %>
    <%= @park.reviews.average(:rating).round(1) %>
    <% else %>
    <%= "N/A" %>
    <% end %>
  </h2>


  <div class="row text-center">
    <ul class="no-bullet text-center small-10 small-centered columns">
      <li class="show-icons">
        <%= image_tag("/images/bathroom.png", size:"40") if @park.bathroom %>
        <%= "Bathrooms Available" if @park.bathroom %>
      </li>
      <li class="show-icons">
        <%= image_tag("/images/picnic.png", size:"40") if @park.picnic %>
        <%= "Picnic Facilities Available" if @park.picnic %>
      </li>
      <li class="show-icons">
        <%= image_tag("/images/pet.png", size:"40") if @park.pets %>
        <%= "Pets Allowed" if @park.pets %>
      </li>
      <li class="show-icons">
        <%= image_tag("/images/basketball.png", size:"40") if @park.basketball %>
        <%= "Basketball Courts Available" if @park.basketball %>
      </li>
      <li class="show-icons">
        <%= image_tag("/images/baseball.png", size:"40") if @park.baseball %>
        <%= "Baseball Field Available" if @park.baseball %>
      </li>
    </ul>
  </div>

  <% if user_signed_in? %>
    <div class="button tiny update-butt">
      <%= link_to 'Update Park Info', edit_park_path(@park) %>
    </div>
  <% end %>
</div>

<div class="text-center">
    <% if current_user.present? && current_user.admin? %>
    <%= link_to 'Delete!', park_path(@park), method: "delete", class: "button tiny update-butt" %>
  <% end %>
</div>

  <ul class="small-10 small-centered column">
    <%= render "reviews/review" %>
  </ul>

  <% unless @reviews.nil? %>
    <%= paginate @reviews %>
  <% end %>

<% if user_signed_in? %>
  <div class="review-title small-8 small-centered column text-center">
    <%= render "reviews/form" %>
  </div>
<% end %>