config/routes.rb
Rails.application.routes.draw do

  Rails.application.routes.draw do
    namespace :api do
      namespace :v1 do
        devise_for :users, controllers: { registrations: 'api/v1/registrations',
                                          sessions:       'api/v1/sessions'}
        resources :votes, only: [:create, :update]
      end
    end
  end

  root 'parks#index'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show]

  resources :parks do
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end

  resources :reviews, only: :none do
    resources :votes, only: [:create, :update]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :review, only: [:edit, :update, :destroy]
  before_action :park, only: [:edit, :update, :destroy]

  def create
    @park = Park.find(params[:park_id])
    @review = @park.reviews.new(review_params)
    @review.user = current_user

    if @review.save
      # ReviewMailer.new_review(@review).deliver_later
      flash[:success] = "Review successfully created!"
      redirect_to park_path(@park)
    else
      flash[:notice] = @review.errors.full_messages
      render 'parks/show'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      flash[:notice] = "You have successfully updated your review!"
      redirect_to @park
    else
      flash.now[:notice] = "Invalid input."
      render 'reviews/edit'
    end
  end

  def destroy
    if @review.destroy
      flash[:notice] = "You have deleted review successfully!"
      redirect_to park_path(@park)
    else
      flash[:notice] = "You failed to delete review!"
      render "parks/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :body, :rating)
  end

  def review
    @review ||= Review.find(params[:id])
  end

  def park
    @park ||= review.park
  end
end

app/views/reviews/_form.html.erb
<h3 class="review-title">Create Review:</h3>
<%= form_for [@park, @review] do |f| %>
  <ul class="review-form-list">
    <%=f.label :title, "Title" %>
    <%= f.text_field :title %>
  </ul>

  <ul class="review-form-list">
    <%= f.label :rating, "Rating" %>
    <%= f.select(:rating, options_for_select([1, 2, 3, 4 ,5 ,6 ,7 ,8, 9, 10])) %>
  </ul>

  <ul class="review-form-list">
    <%=f.label :body, "Body" %>
    <%= f.text_field :body %>
  </ul>

  <ul class="review-form-list">
    <%= f.submit class: "button tiny"%>
  </ul>
<% end %>

app/views/reviews/_review.html.erb
<% unless @reviews.nil? %>
<% @reviews.each do |review|%>
  <% if !review.id.nil?%>
    <div class="list-item">
      <div class="row" data-equalizer>

        <li>
          <div class="review-info small-4 column" data-equalizer-watch>
            <p>
              <%= review.title %><br>
              Rating: <%= review.rating %><br>
              <% unless current_user.nil? %>
                <% if current_user == review.user || current_user.admin? %>
                  <%= link_to 'Edit / ', edit_park_review_path(@park, review)%>
                  <%= link_to 'Delete', park_review_path(@park, review), method: :delete%>
                <% end %>
              <% end %>
            </p>
          </div>
          <div class="review-body small-5 column" data-equalizer-watch>
            <p><%= review.body %></p>
          </div>
          <div class="review-rating small-3 column text-center" data-equalizer-watch>
            <p>
              <% flag = false %>
              <% if current_user.nil?%>
                vote count: <%= review.vote_count%>
              <% end %>
              <% if !current_user.nil?%>
                <% if !review.votes.nil? && !current_user.nil? %>
                  <% review.votes.each do |vote|%>
                    <% if vote.user_id == current_user.id %>
                      <% flag = true %>
                    <% end %>
                  <% end %>
                <% end %>

                <% if flag %>
                  <div class="update-button-<%= review.id %>">
                    <%= button_to 'Up', {controller: "votes", action: "update", park_id: @park.id, review_id: review.id, vote: "up"} , method: :patch, id: "update-up", data: {park_id: @park.id, review_id: review.id, user_id: current_user.id, vote_id: review.votes.where(user: current_user).first}, class: "button tiny vote"%>
                    <div class="vote-count-<%= review.id %>">
                      Vote Count: <%= review.vote_count%>
                    </div>
                    <%= button_to 'Down', {controller: "votes", action: "update", park_id: @park.id, review_id: review.id, vote: "down"} , method: :patch , id: "update-down", data: {park_id: @park.id, review_id: review.id, user_id: current_user.id, vote_id: review.votes.where(user: current_user).first}, class: "button tiny vote" %>
                  </div>
                <% else %>
                  <div class="create-button-<%= review.id %>">
                    <%= button_to 'Up', {controller: "votes", action: "create", park_id: @park.id, review_id: review.id, vote: "up"} , method: :post, class: "create-up button tiny vote",  id: "create-up-#{review.id}", data: { park_id: @park.id, review_id: review.id, user_id: current_user.id , vote_id: review.votes.where(user: current_user).first} %>
                    <div class="vote-count-<%= review.id %>">
                      Vote Count: <%= review.vote_count%>
                    </div>
                    <%= button_to 'Down', {controller: "votes", action: "create", park_id: @park.id, review_id: review.id, vote: "down"} , method: :post, class: "create-down button tiny vote", id: "create-down-#{review.id}", data: {park_id: @park.id, review_id: review.id, user_id: current_user.id, vote_id: review.votes.where(user: current_user).first }%>
                  </div>
                <% end %>
              <% end %>
            </p>
          </div>
        </li>
      </div>
    </div>
  <% end %>
<% end %>
<% end %>

app/views/reviews/edit.html.erb
<div class="review-title small-8 small-centered column text-center">
  <h1 class="review-title">Edit Review Form</h1>
  <%= render "reviews/form" %>
</div>